apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
   - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: "man"
  hostPath:
   path: "/mongodb"
  claimRef:
    name: mongo-pvc
    namespace: coffee
  
--- 

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
  namespace: coffee
spec:
  storageClassName: "man" 
  volumeName: mongo-pv
  accessModes:
    - ReadWriteOnce
    
  resources:
    requests:
      storage: 5Gi